### ISSUE TITLE
Is a small proportion of bursting cycles normal?

### ISSUE THREAD

**Issue by ShuangquanFeng** [bycycle-tools/bycycle#43]
Even when I set the burst_kwargs parameter to be relatively low (e.g. 0.2, 0.3, 0.4, and 0.8 respectively), the proportion of bursting cycles was only still approximately 1/6. Is that normal? Does more bursting cycles imply more information contained in the by-cycle analysis results and more neuroscientifically interesting? I noticed that in tutorial 3, only bursting cycles are included in the comparison of features between patients and controls. If I do a similar comparison, will the result be somewhat biased because only a small proportion of cycles are labeled as "bursting" when the detection threshold was relatively low?

**Comment by nschawor** [comment]
For a cycle to be considered as a burst, **all** the criteria in the burst_kwargs dictionary have to be fulfilled simultaneously. This could easily be only a fraction of cycles, so that is indeed normal! 

The number of cycles which contain oscillatory bursts depends on the nature of the rhythm, a sustained occipital alpha will have more cycles compared to more transient sensorimotor mu-rhythm, for instance. So it depends on the scientific question, brain area, behavioral state. 

For some (if not most) questions, it makes sense to only retain the burst cycles, e.g. if you want to compare the waveform shape of oscillations, since for that, there has to be an oscillation. For illustration, I recommend to plot the cycles with the lowest voltage amplitude and check their time course in contrast to cycles with higher amplitude values, it helps to get an intuition for the cycle parameters.
