### ISSUE TITLE
Bycycle Group Analysis

### ISSUE THREAD

**Issue by ryanhammonds** [bycycle-tools/bycycle#52]
Stephanie has suggested functionality to more easily facilitate an analysis for epoched event-related data. This would mean a implementation similar to ```FOOOFGroup```, but for a group of time series. It may be useful to have an additional column in the pandas dataframe that indicates the trial type of each segment of the signal (row).

**Comment by TomDonoghue** [comment]
This sound like a good idea, but just a note that I think there are perhaps two different things here:
- 2d arrays of channels (multiple channels across time)
- 3d arrays of channels (split up into epochs)

By comparison to FOOOF,  FOOOFGroup does 2d arrays of spectra, which is equivalent to multiple channels, but this is not epoched. One there is functionality for 2D arrays, epochs can be run by a helper function to distribute each epoch (2d array) into the 2d functionality (in fooof `fit_fooof_3d` does this, applying FOOOFGroups to 2d arrays from a 3d input). 

As I understand it, ByCycle right now takes in a single channel, so this ideas can mean both generalizing ByCycle to run across multiple channels, and/or generalizing ByCycycle to run across multiple segments (epochs), for one or many channels.

**Comment by nschawor** [comment]
The most useful approach for the moment would be a group analysis across epochs, since here the parameters for burst detection should be kept the same but burst detection should be performed simultaneously across the different epochs (e.g. considering a global ```amp_fraction```). 

Since channels have different SNR, they will require adjustment of burst detection parameters per channel and can be processed independently. 

So currently, it is possible to do the latter by just calling ```compute_features``` in a loop, but the former is trickier at the moment, since burst detection will be performed independently for each epoch. Would focus on the epoch-based scenario for now. (& maybe convenience wrapper for channel-based at some later point in time)

**Comment by ryanhammonds** [comment]
This was addressed in #64 (`bycycle.group.compute_features_2d` and `bycycle.group.compute_features_3d`). These funcs allow flexible burst detection parameters across axes in either 2d or 3d arrays (i.e. one single set of params for all signals or unique sets of params across different axes/signals). The docstring examples demonstrate usage, but an additional tutorial may be useful. Lastly, these function have been parallelized using the multiprocessing module, which may be useful for large arrays.

I'll leave this open until these funcs are confirmed stable / useful, maybe until the next release.
